### ISSUE TITLE
Build an auto-attester

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/prototype-services#38]
This should be a cli script, which takes the seed of an Attester and the ctype, he should attest automatically.
The script polls the messaging service regularly and makes an attestation, when an attestation for the specified ctype is requested.

THIS IS NOT PART OF THE SERVICES SERVER
Every user can start this for themselves

**Comment by csmarc** [comment]
Can we close this?

**Comment by tjwelde** [comment]
this is done
